### ISSUE TITLE
[Meta] clean up

### ISSUE THREAD

**Issue by GeopJr** [GeopJr/Tooth#7]
- [ ] (in)install scripts should instead be in a makefile or similar

- [x] get rid of screenshots and other big files

- [x] fix ci

- [x] update manifests, metadata and screenshots

- [ ] update Po files

(More might be added)
